sudo: required
jdk: openjdk8
services:
- docker
install:
- sudo apt-get -qq update
- sudo apt-get -qq -y install graphviz realpath
- curl -fsSL get.nextflow.io | bash
- docker pull nextflow/examples
script: 
- ./nextflow run main.nf -with-docker
